version: "3.8"

networks:
  examination_system:
    driver: bridge

services:
  examination_system_db:
    image: mysql
    container_name: examination_system.db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: exam_sym
    ports:
      - "4315:3306"
    expose:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - examination_system

  examination_system_web:
    image: examination_system.web
    build:
      context: .
      dockerfile: ExaminationSystem.Web/Dockerfile
    
    container_name: examination_system_web
    ports:
      - "4317:4317"
    expose:
      - "4317"
    volumes:
      - ./logs:/app/Logs
    environment:
#      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Mysql=server=examination_system_db;port=3306;database=exam_sym;userid=root;password=123456
    depends_on:
      - examination_system_db
    restart: always
    
    networks:
      - examination_system
        
  #监控
  examination_system_health:
    image: examination_system.health_dashboard
    build:
      context: .
      dockerfile: ExaminationSystem.HealthDashboard/Dockerfile
      
    container_name: examination_system_health_dashboard
    ports:
      - "4318:4318"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # 监听      
      - HealthCheckEndpoints__ExaminationSystem=http://examination_system_web:4317/healthz
    depends_on:
      - examination_system_web
    restart: always
    networks:
      - examination_system

