version: "3.8"

networks:
  examination_system:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: examination_system.mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: exam_sym
    ports:
      - "4315:3306"
    expose:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - examination_system


#  #迁移项目
#  migrator:
#    image: examination_system.migrator
#    build:
#      context: .
#      dockerfile: ExaminationSystem.Migrator/Dockerfile
#    container_name: examination_system_migrator
#    #    ports:
#    #      - "4316:4316"
#    #    expose:
#    #      - "4316"
#    environment:
#      - ConnectionStrings__Mysql=server=mysql;port=3306;database=exam_sym;userid=root;password=123456
#    depends_on:
#      - mysql
#    networks:
#      - examination_system
#  
  
  web:
    image: examination_system.web
    build:
      context: .
      dockerfile: ExaminationSystem.Web/Dockerfile
    
    container_name: examination_system_web
    ports:
      - "4317:4317"
    expose:
      - "4317"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Mysql=server=mysql;port=3306;database=exam_sym;userid=root;password=123456
    depends_on:
      - mysql
#      - migrator
    restart: always
    networks:
      - examination_system
        
        

      
